# This checks for a transitive relationship through PROVO and GITO instances

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX git:  <http://www.interition.net/sccs/git/ref/> 
PREFIX sci:  <http://www.interition.net/sccs/git/id/sccs.git/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

PREFIX scf: <file://www.interition.net/sparqlycode/sccs.git/> # prefix with file do not appear to work.

#SELECT ?_commit ?_file {
ASK WHERE {
	
	?_commit prov:wasAssociatedWith ?_person ; 
		prov:endedAtTime ?Time .
	?_person foaf:name ?Name .
	
	?_commit git:difference/git:isModified true ;
		git:difference/git:file ?_file .
	
}