# This is just for playing with the commit history chain

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?Commit ?ParentCommit  WHERE {
#ASK WHERE {
	?_commit rdfs:label "820218802a6e66f3acb4ad35a8daeb1f001590ff"  .
	
	?_commit  prov:wasInformedBy+ ?_parentCommit ; rdfs:label ?Commit .
	
	?_parentCommit rdfs:label ?ParentCommit .

}