# This checks that prov:Activity have related prov:Entity

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>

ASK WHERE {
	?_commit a prov:Activity ;
			prov:used ?thing .
    ?thing a prov:Entity .
}