/* CVS $Id: $ */
package net.interition.sparlycode.model; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /Users/pjworrall/Documents/Java2RDF/sparqlycode/sparqlycode-sccs-git/src/main/resources/GITO.ttl 
 * @author Auto-generated by schemagen on 05 Mar 2015 20:03 
 */
public class GITO {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.interition.net/sccs/git/ref/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property author = m_model.createProperty( "http://www.interition.net/sccs/git/ref/author" );
    
    public static final Property difference = m_model.createProperty( "http://www.interition.net/sccs/git/ref/difference" );
    
    public static final Property file = m_model.createProperty( "http://www.interition.net/sccs/git/ref/file" );
    
    public static final Property isAdded = m_model.createProperty( "http://www.interition.net/sccs/git/ref/isAdded" );
    
    public static final Property isCopied = m_model.createProperty( "http://www.interition.net/sccs/git/ref/isCopied" );
    
    public static final Property isDeleted = m_model.createProperty( "http://www.interition.net/sccs/git/ref/isDeleted" );
    
    public static final Property isModified = m_model.createProperty( "http://www.interition.net/sccs/git/ref/isModified" );
    
    public static final Property isRenamed = m_model.createProperty( "http://www.interition.net/sccs/git/ref/isRenamed" );
    
    public static final Property parent = m_model.createProperty( "http://www.interition.net/sccs/git/ref/parent" );
    
    public static final Property tree = m_model.createProperty( "http://www.interition.net/sccs/git/ref/tree" );
    
    public static final Resource Branch = m_model.createResource( "http://www.interition.net/sccs/git/ref/Branch" );
    
    public static final Resource Commit = m_model.createResource( "http://www.interition.net/sccs/git/ref/Commit" );
    
    public static final Resource File = m_model.createResource( "http://www.interition.net/sccs/git/ref/File" );
    
    public static final Resource Remote = m_model.createResource( "http://www.interition.net/sccs/git/ref/Remote" );
    
    public static final Resource Tag = m_model.createResource( "http://www.interition.net/sccs/git/ref/Tag" );
    
    public static final Resource Tree = m_model.createResource( "http://www.interition.net/sccs/git/ref/Tree" );
    
    public static final Resource Author = m_model.createResource( "http://www.interition.net/sccs/git/ref/Author" );
    
    public static final Resource Committer = m_model.createResource( "http://www.interition.net/sccs/git/ref/Committer" );
    
}
